<?php
namespace ADS\WCCR;
defined( 'ABSPATH' ) || exit;
/**
 * Class NameList
 *
 * Provides a list of names for use in reviews.
 */

class NameList {
    public static function get_names(): array {
        $reviewer = [
            'james_smith'       => 'James Smith',
            'emily_johnson'     => 'Emily Johnson',
            'oliver_brown'      => 'Oliver Brown',
            'harry_evans'       => 'Harry Evans',
            'amelia_clarke'     => 'Amelia Clarke',
            'jack_wilson'       => 'Jack Wilson',
            'olivia_moore'      => 'Olivia Moore',
            'charlie_hughes'    => 'Charlie Hughes',
            'mia_walker'        => 'Mia Walker',
            'alfie_hall'        => 'Alfie Hall',
            'ava_green'         => 'Ava Green',
            'george_king'       => 'George King',
            'isla_baker'        => 'Isla Baker',
            'noah_wright'       => 'Noah Wright',
            'sophie_scott'      => 'Sophie Scott',
            'leo_morris'        => 'Leo Morris',
            'grace_wood'        => 'Grace Wood',
            'archie_thomas'     => 'Archie Thomas',
            'ruby_harris'       => 'Ruby Harris',
            'freddie_lewis'     => 'Freddie Lewis',
            'lily_clark'        => 'Lily Clark',
            'oscar_robinson'    => 'Oscar Robinson',
            'chloe_james'       => 'Chloe James',
            'theo_white'        => 'Theo White',
            'ella_martin'       => 'Ella Martin',
            'henry_jackson'     => 'Henry Jackson',
            'poppy_turner'      => 'Poppy Turner',
            'joshua_cooper'     => 'Joshua Cooper',
            'evie_hill'         => 'Evie Hill',
            'archie_edwards'    => 'Archie Edwards',
            'isabella_mitchell' => 'Isabella Mitchell',
            'lucas_carter'      => 'Lucas Carter',
            'daisy_phillips'    => 'Daisy Phillips',
            'logan_parker'      => 'Logan Parker',
            'sienna_adams'      => 'Sienna Adams',
            'ethan_collins'     => 'Ethan Collins',
            'millie_bennett'    => 'Millie Bennett',
            'alexander_watson'  => 'Alexander Watson',
            'rosie_wright'      => 'Rosie Wright',
            'mason_brooks'      => 'Mason Brooks',
            'holly_wood'        => 'Holly Wood',
            'finley_harrison'   => 'Finley Harrison',
            'lola_hughes'       => 'Lola Hughes',
            'benjamin_ward'     => 'Benjamin Ward',
            'matilda_cox'       => 'Matilda Cox',
            'samuel_richards'   => 'Samuel Richards',
            'erin_gray'         => 'Erin Gray',
            'jake_patel'        => 'Jake Patel',
            'scarlett_kelly'    => 'Scarlett Kelly',
            'harvey_barnes'     => 'Harvey Barnes',
            'florence_murray'   => 'Florence Murray',
            'lucy_reed'         => 'Lucy Reed',
            'sebastian_hart'    => 'Sebastian Hart',
            'ella_bradley'      => 'Ella Bradley',
            'daniel_shaw'       => 'Daniel Shaw',
            'ruby_mason'        => 'Ruby Mason',
            'thomas_holmes'     => 'Thomas Holmes',
            'sophia_burton'     => 'Sophia Burton',
            'matthew_bailey'    => 'Matthew Bailey',
            'hannah_elliott'    => 'Hannah Elliott',
            'lewis_ross'        => 'Lewis Ross',
            'amelie_foster'     => 'Amelie Foster',
            'ryan_hamilton'     => 'Ryan Hamilton',
            'phoebe_matthews'   => 'Phoebe Matthews',
            'dylan_harvey'      => 'Dylan Harvey',
            'ella_henderson'    => 'Ella Henderson',
            'mohammed_ali'      => 'Mohammed Ali',
            'summer_bell'       => 'Summer Bell',
            'adam_hunter'       => 'Adam Hunter',
            'ivy_mills'         => 'Ivy Mills',
            'joseph_bradley'    => 'Joseph Bradley',
            'willow_pearson'    => 'Willow Pearson',
            'tyler_bishop'      => 'Tyler Bishop',
            'elsie_owen'        => 'Elsie Owen',
            'harriet_ward'      => 'Harriet Ward',
            'michael_elliott'   => 'Michael Elliott',
            'nancy_holmes'      => 'Nancy Holmes',
            'leon_evans'        => 'Leon Evans',
            'mila_hart'         => 'Mila Hart',
            'zachary_bennett'   => 'Zachary Bennett',
            'rose_morgan'       => 'Rose Morgan',
            'jenson_hall'       => 'Jenson Hall',
            'maddison_bailey'   => 'Maddison Bailey',
            'hugo_mason'        => 'Hugo Mason',
            'ellie_bell'        => 'Ellie Bell',
            'reuben_barker'     => 'Reuben Barker',
            'lucy_mills'        => 'Lucy Mills',
            'frankie_ward'      => 'Frankie Ward',
            'martha_harrison'   => 'Martha Harrison',
            'toby_harvey'       => 'Toby Harvey',
            'lottie_hunter'     => 'Lottie Hunter',
            'jude_pearson'      => 'Jude Pearson',
            'mary_bishop'       => 'Mary Bishop',
            'arthur_owen'       => 'Arthur Owen',
            'eliza_ward'        => 'Eliza Ward',
            'rory_elliott'      => 'Rory Elliott',
            'sarah_holmes'      => 'Sarah Holmes',
            'alfie_evans'       => 'Alfie Evans',
            'penny_hart'        => 'Penny Hart',
            'jasmine_bennett'   => 'Jasmine Bennett',
            'callum_morgan'     => 'Callum Morgan'
        ];

        return $reviewer;
    }
}
